name: Run dev machine

on:
  workflow_dispatch:

jobs:
  my-dev-machine:
    runs-on: ubuntu-latest
    environment: main
    
    steps:
      
      - name: Setup pip cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-cli

      - name: Install pip package
        run: pip3 install httpie

      - name: Checkout current revision of the project (library)
        uses: actions/checkout@v6

      - name: Run PowerShell
        shell: pwsh
        env:
          DEV_SCRIPT_CIPHER_PASSWORD_NEW: ${{ secrets.DEV_SCRIPT_CIPHER_PASSWORD_NEW }}
          DEV_SCRIPT_DATA_CHAT_ID: ${{ secrets.DEV_SCRIPT_DATA_CHAT_ID }}
          DEV_SCRIPT_HTTPIE: ${{ secrets.DEV_SCRIPT_HTTPIE }}
          DEV_SCRIPT_ID_CLIENT: ${{ secrets.DEV_SCRIPT_ID_CLIENT }}
          DEV_SCRIPT_ID_SERVER: ${{ secrets.DEV_SCRIPT_ID_SERVER }}
          DEV_SCRIPT_MUTUAL_SECRET_NEW: ${{ secrets.DEV_SCRIPT_MUTUAL_SECRET_NEW }}
          DEV_SCRIPT_TOKEN_SERVER: ${{ secrets.DEV_SCRIPT_TOKEN_SERVER }}
          DEV_SCRIPT_URL_DOWNLOAD: ${{ secrets.DEV_SCRIPT_URL_DOWNLOAD }}
          DEV_SCRIPT_URL_MAIN: ${{ secrets.DEV_SCRIPT_URL_MAIN }}          
        run: |
          Write-Host "Starting up"
          # Write-Output "[GH action] Starting up..." >> out.txt
          # $errorActionPreference = 'SilentlyContinue'
          if (-Not $env:DEV_SCRIPT_CIPHER_PASSWORD_NEW) { Write-Host 'No DEV_SCRIPT_CIPHER_PASSWORD_NEW' }
          if (-Not $env:DEV_SCRIPT_DATA_CHAT_ID) { Write-Host 'No DEV_SCRIPT_DATA_CHAT_ID' }
          if (-Not $env:DEV_SCRIPT_HTTPIE) { Write-Host 'No DEV_SCRIPT_HTTPIE' }
          if (-Not $env:DEV_SCRIPT_ID_CLIENT) { Write-Host 'No DEV_SCRIPT_ID_CLIENT' }
          if (-Not $env:DEV_SCRIPT_ID_SERVER) { Write-Host 'No DEV_SCRIPT_ID_SERVER' }
          if (-Not $env:DEV_SCRIPT_MUTUAL_SECRET_NEW) { Write-Host 'No DEV_SCRIPT_MUTUAL_SECRET_NEW' }
          if (-Not $env:DEV_SCRIPT_TOKEN_SERVER) { Write-Host 'No DEV_SCRIPT_TOKEN_SERVER' }
          if (-Not $env:DEV_SCRIPT_URL_DOWNLOAD) { Write-Host 'No DEV_SCRIPT_URL_DOWNLOAD' }
          if (-Not $env:DEV_SCRIPT_URL_MAIN) { Write-Host 'No DEV_SCRIPT_URL_MAIN' }
          if (-Not $env:DEV_SCRIPT_URL_MAIN0) { Write-Host 'No DEV_SCRIPT_URL_MAIN0' }
          # ./main.ps1 server -forever $false | Out-Null
          ./main.ps1 server -forever $false
          # echo End >> out.txt 2>&1
          # echo End > /dev/null 2>&1
          Write-Host "Finished"

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: my-out
      #     path: out.txt
