name: Run dev machine

on:
  workflow_dispatch:

jobs:
  my-dev-machine:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Setup pip cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-cli

      - name: Install pip package
        run: pip3 install httpie

      - name: Run PowerShell
        shell: pwsh
        run: |
          Write-Host "ok there"
          Write-Output "Start again" >> out.txt
          python3 --version >> out.txt
          pip3 show httpie >> out.txt
          python3 -m httpie -h https://www.youtube.com >> out.txt
          pip3 cache info >> out.txt
          ls ~/.cache/pip >> out.txt 2>&1

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: my-out
          path: out.txt
