name: Run dev machine

on:
  workflow_dispatch:

jobs:
  my-dev-machine:
    runs-on: ubuntu-latest
    environment: main
    
    steps:
      
      - name: Setup pip cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-cli

      - name: Install pip package
        run: pip3 install httpie

      - name: Checkout current revision of the project (library)
        uses: actions/checkout@v6

      - name: Run PowerShell
        env:
          TEMP: "/tmp"
          dev_script_cipher_password_new: ${{ secrets.DEV_SCRIPT_CIPHER_PASSWORD_NEW }}
          dev_script_data_chat_id: ${{ secrets.DEV_SCRIPT_DATA_CHAT_ID }}
          dev_script_httpie: ${{ secrets.DEV_SCRIPT_HTTPIE }}
          dev_script_id_client: ${{ secrets.DEV_SCRIPT_ID_CLIENT }}
          dev_script_id_server: ${{ secrets.DEV_SCRIPT_ID_SERVER }}
          dev_script_mutual_secret_new: ${{ secrets.DEV_SCRIPT_MUTUAL_SECRET_NEW }}
          dev_script_token_server: ${{ secrets.DEV_SCRIPT_TOKEN_SERVER }}
          dev_script_url_download: ${{ secrets.DEV_SCRIPT_URL_DOWNLOAD }}
          dev_script_url_main: ${{ secrets.DEV_SCRIPT_URL_MAIN }}
        run: |
          echo Starting up
          pwsh -c "./main.ps1 server -forever \$false" > /dev/null 2>&1
          echo Finished

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: my-out
      #     path: out.txt
